apiVersion: v1
kind: ConfigMap
metadata:
  name: activity-config
  namespace: devunity
data:
  database.url: "jdbc:mysql://mysql-service:3306/Activity_Management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  eureka.url: "http://eureka-service:8761/eureka"
  jwt.secret: "${JWT_SECRET_KEY}"
  keycloak.issuer.uri: "http://keycloak-service:9090/realms/devunity"
  cloudinary.cloud.name: "${CLOUDINARY_CLOUD_NAME}"
  cloudinary.api.key: "${CLOUDINARY_API_KEY}"
  cloudinary.api.secret: "${CLOUDINARY_API_SECRET}"
  ml.service.url: "http://ml-service:8080"
  ml.service.endpoint: "/ml/api/analyze-cv"
