apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devunity
type: Opaque
data:
  # root (base64 encoded)
  username: cm9vdA==
  # password (base64 encoded - empty string)
  password: ""
  # root-password for MySQL root user (base64 encoded)
  root-password: cm9vdHBhc3N3b3Jk
