spring.application.name=social-interaction-service

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/Social_Interaction?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.config.enabled=false

server.servlet.context-path=/socials/api

logging.level.feign=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.com.netflix.discovery=DEBUG
logging.level.com.netflix.loadbalancer=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG

# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration,org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
#spring.elasticsearch.uris=https://localhost:9200
#spring.elasticsearch.username=elastic
#spring.elasticsearch.password=SJ3Abz3qKoD4t1mqb+st
#spring.data.elasticsearch.repositories.enabled=true
#spring.elasticsearch.ssl.verification-mode=none

management.endpoints.web.exposure.include=health,prometheus,metrics,info
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

