package tn.esprit.employee.Entities;

public enum NotificationType {
    INFO, SUCCESS, WARNING, ERROR,
    APPLICANT_CREATED, APPLICANT_UPDATED, APPLICANT_STATUS_CHANGED,
    INTERVIEW_SCHEDULED, INTERVIEW_UPDATED, INTERVIEW_CANCELLED, INTERVIEW_REMINDER,
    RECRUITMENT_CREATED, RECRUITMENT_CLOSED, RECRUITMENT_STATUS_CHANGED,
    GENERAL
}
