apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "social-interaction.fullname" . }}
  labels:
    {{- include "social-interaction.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "social-interaction.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "social-interaction.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.config.dbUrl | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.config.dbUsername | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.config.dbPassword | quote }}
            - name: SPRING_ELASTICSEARCH_URIS
              value: {{ .Values.config.elasticsearchUrl | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
