apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "social-interaction.fullname" . }}
  namespace: dev-unity
  labels:
    {{- include "social-interaction.labels" . | nindent 4 }}
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - dev-unity
  selector:
    matchLabels:
      {{- include "social-interaction.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /socials/api/actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s