pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven'
    }

    environment {
        JAVA_HOME = "${tool 'JDK17'}"
        PATH = "${JAVA_HOME}/bin:${env.PATH}"
        NEXUS_URL = "http://192.168.232.133:8081"
        BACKEND_PATH = "Back-PIDEV-4SAE7-2026-DEVUNITY"

        DOCKER_REGISTRY = "hibajassi123"
        IMAGE_NAME = "community-service"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Récupération du code...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Compilation Maven...'
                dir("${BACKEND_PATH}/Community_Engagement_Service") {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Deploy Community') {
            steps {
                echo 'Déploiement vers Nexus...'
                dir("${BACKEND_PATH}/Community_Engagement_Service") {

                    withCredentials([usernamePassword(
                        credentialsId: 'nexus-credentials',
                        usernameVariable: 'NEXUS_USER',
                        passwordVariable: 'NEXUS_PASS'
                    )]) {

                        sh """
                        cat > settings.xml <<EOF
<settings>
  <servers>
    <server>
      <id>nexus</id>
      <username>${NEXUS_USER}</username>
      <password>${NEXUS_PASS}</password>
    </server>
  </servers>
</settings>
EOF

                        mvn deploy -DskipTests \
                        --settings settings.xml \
                        -DaltDeploymentRepository=nexus::default::${NEXUS_URL}/repository/devunity-repo/
                        """
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Construction de l’image Docker...'
                dir("${BACKEND_PATH}/Community_Engagement_Service") {
                    sh """
                        docker build -t ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest .
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'Build réussi !'
        }
        failure {
            echo 'Build échoué !'
        }
        always {
            cleanWs()
        }
    }
}