pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven'
    }

    environment {
        JAVA_HOME = "${tool 'JDK17'}"
        PATH = "${JAVA_HOME}/bin:${env.PATH}"

        REGISTRY_CREDENTIAL = "REGISTRY_CREDENTIAL"

        NEXUS_URL  = "http://192.168.232.133:8081"
        NEXUS_REPO = "devunity-repo"

        DOCKER_REGISTRY = "hibajassi123"

        BACKEND_PATH = "Back-PIDEV-4SAE7-2026-DEVUNITY"
        SERVICE_PATH = "Community_Engagement_Service"
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Récupération du code...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Compilation Maven...'

                dir("${BACKEND_PATH}/${SERVICE_PATH}") {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Deploy to Nexus') {
            steps {
                echo 'Déploiement vers Nexus...'

                dir("${BACKEND_PATH}/${SERVICE_PATH}") {

                    withCredentials([
                        usernamePassword(
                            credentialsId: 'nexus-credentials',
                            usernameVariable: 'NEXUS_USER',
                            passwordVariable: 'NEXUS_PASS'
                        )
                    ]) {

                        sh """
cat > settings.xml <<EOF
<settings>
  <servers>
    <server>
      <id>nexus</id>
      <username>${NEXUS_USER}</username>
      <password>${NEXUS_PASS}</password>
    </server>
  </servers>
</settings>
EOF

mvn deploy -DskipTests \
  --settings settings.xml \
  -DaltDeploymentRepository=nexus::default::${NEXUS_URL}/repository/${NEXUS_REPO}/
"""
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                script {

                    dockerImageCommunity = docker.build(
                        "${DOCKER_REGISTRY}/community-engagement-service:${BUILD_NUMBER}",
                        "--no-cache -f ${BACKEND_PATH}/Community_Engagement_Service/Dockerfile ."
                    )

                }
            }
        }

        stage('Push Docker Images') {
            steps {
                script {

                    docker.withRegistry('', REGISTRY_CREDENTIAL) {

                        retry(3) {

                            dockerImageCommunity.push("${BUILD_NUMBER}")
                            dockerImageCommunity.push('latest')

                        }
                    }
                }
            }
        }
    }

    post {

        success {
            echo 'Pipeline terminé avec succès !'
        }

        failure {
            echo 'Pipeline échoué !'
        }

        always {
            cleanWs()
        }
    }
}