pipeline {
    agent any

    tools {
        maven "maven3"   // ⚠️ doit matcher Jenkins
        jdk "jdk17"      // ⚠️ ou configure JDK21 dans Jenkins
    }

    environment {
        SONAR_HOST_URL = "http://sonarqube:9000"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/saifelislem/Esprit-PIDEV-4SAE7-2026-DEVUNITY.git'
            }
        }

        stage('Clean Build') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'mvn test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh """
                        mvn sonar:sonar \
                        -Dsonar.projectKey=activity-management-service \
                        -Dsonar.projectName=ActivityManagementService
                    """
                }
            }
        }

        stage('Build Package') {
            steps {
                sh 'mvn package -DskipTests'
            }
        }
    }
}