apiVersion: apps/v1
kind: Deployment
metadata:
  name: academic-management-service
  namespace: devunity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academic-management-service
  template:
    metadata:
      labels:
        app: academic-management-service
    spec:
      containers:
        - name: academic-management-service
          image: chaibimarwa/academic-management-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service.devunity.svc.cluster.local:3306/Academic_Management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"  # ✅ full DNS
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.MySQL8Dialect"   # ✅ fixes Dialect error
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server.devunity.svc.cluster.local:8761/eureka"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak-service.devunity.svc.cluster.local:8080/realms/devunity"
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "http://keycloak-service.devunity.svc.cluster.local:8080"
            - name: KEYCLOAK_REALM
              value: "devunity"
            - name: KEYCLOAK_RESOURCE
              value: "devunity-app"
            - name: KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak-admin-username  # ✅ moved to secret
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: keycloak-admin-password  # ✅ moved to secret
            - name: SERVER_PORT
              value: "8083"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/academics/api"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: academic-management-svc
  namespace: devunity
spec:
  selector:
    app: academic-management-service
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
