apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: devunity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: chaibimarwa/api-gateway:latest
          ports:
            - containerPort: 8081  # gateway
            - containerPort: 8082  # actuator/prometheus
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server.devunity.svc.cluster.local:8761/eureka"  # ✅ full DNS
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: MANAGEMENT_SERVER_PORT
              value: "8082"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: "api-gateway"

          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: devunity
spec:
  selector:
    app: api-gateway
  type: NodePort
  ports:
    - name: gateway
      port: 8081
      targetPort: 8081
      nodePort: 30007
    - name: actuator
      port: 8082
      targetPort: 8082  # ✅ expose actuator port