apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: devunity
data:
  init.sql: |
    CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root123';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;