apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devunity
type: Opaque
stringData:
  mysql-root-password: "root123"
  mysql-database: "Academic_Management"
  mysql-username: "root"