apiVersion: v1
kind: Service

metadata:
  name: devunity-frontend-service
  namespace: devunity

spec:
  type: NodePort

  selector:
    app: devunity-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080