apiVersion: apps/v1
kind: Deployment

metadata:
  name: devunity-frontend
  namespace: devunity

spec:
  replicas: 1

  selector:
    matchLabels:
      app: devunity-frontend

  template:
    metadata:
      labels:
        app: devunity-frontend

    spec:
      containers:
        - name: devunity-frontend

          image: chelba/dev-unity-frontend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 80