spring.application.name=activity-management-service

spring.datasource.url=jdbc:mysql://localhost:3306/Activity_Management?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Base_Securisee_123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
management.health.mail.enabled=false


server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.config.enabled=false

server.error.include-message=always
server.error.include-stacktrace=always

server.servlet.context-path=/activities/api

cloudinary.cloud_name=ddtfi7kal
cloudinary.api_key=971417699379591
cloudinary.api_secret=SzcF1Ll17RR2oMvueIXikFAN2IM

logging.level.feign=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.com.netflix.discovery=DEBUG
logging.level.com.netflix.loadbalancer=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:[email]}
spring.mail.password=${EMAIL_PASSWORD:[app_password]}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Application Email
app.mail.from=${EMAIL_USERNAME:[email]}
app.mail.enabled=true

# JWT Security (Synchronized with DevUnity)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

# JWT Security (Keycloak Validation via RSA / JWKS)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/devunity
