apiVersion: apps/v1
kind: Deployment
metadata:
  name: community
  namespace: devunity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community
  template:
    metadata:
      labels:
        app: community
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql-service.devunity.svc.cluster.local 3306; do echo waiting for mysql; sleep 3; done']
      containers:
        - name: community
          image: hibajassi123/community-engagement-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service.devunity.svc.cluster.local:3306/Academic_Management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"  # ✅ full DNS
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.MySQL8Dialect"   # ✅ fixes Dialect error
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server.devunity.svc.cluster.local:8761/eureka"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak-service.devunity.svc.cluster.local:8080/realms/devunity"
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "http://keycloak-service.devunity.svc.cluster.local:8080"
            - name: KEYCLOAK_REALM
              value: "devunity"
            - name: KEYCLOAK_RESOURCE
              value: "devunity-app"
            - name: KEYCLOAK_ADMIN_USERNAME
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin123"
            - name: SERVER_PORT
              value: "8084"


          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: community-svc
  namespace: devunity
spec:
  selector:
    app: community
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30084